language: ruby
rvm:
- 2.3.3
deploy:
  provider: heroku
  api_key:
    secure: NGwPZH6v+zsWt6BteF5gZ07rgq6qmPisjMOOjr25VxuLYVH211gzC3FwXE/Nmsmr12ihXBJEHrLe0ZnVa8yMRkls6Gjem7hWJyn5RSXp26dx4r4GkKNBdZ2O80MbUMyRFg3Qz0w9dsFC29XUh5nGE0X3EO/3YN0guEPCVenQ5K/vcUO37RbF/QGpUUHLMby8D+QU0r3bUsc6TnCqNqf4+N+Z/BhFp7wKA1erKrxHuc+gV3nquPm+ZpWM8J8xmmst1v3qjWYihjF1ZXJKwekdzgk9TbjasJGFWWeWoMvJs1OA5oXXLZz0Cq5KVFCXqrZcE71XgwKPJ4DVMn9YIMhNS15rropJgNFMrAcGGzgTIEApyIEPmmvrILHvGeRYGNH0I+L3XxSOS0MUizW0ww/AkKyVGfK2dChh1xkhJl5sTkkixjHSE9YVj+ml9SFOtFTn7Xj/cPGq1cVSmHvRGrGra0I+dlewbQ+VYNqEEjPOO0x5YUOkvZedOffOL/y6nEt0AslcrmdWx4kkiIFYAGKeWBhuqmQCTQ2BpL8WN/iObH6KTdp7THn2iG5pFkLDcLW0kMHWFLORKNQSTOHGvuDs3I5BMusW3z30N29TsiesJfbsnQ/+aqGLSSvxVgeDPFd6Ppv5CZTWJ2W6swhBEOwdlVTO4CFsEGiou2BYtohNi14=
  app: railspapillier
before install: gem install bundler