
development:
  adapter: postgresql
  encoding: unicode
  database: Project_Rails
  username: postgres
  password: rp07051998

test:
  adapter: postgresql
  encoding: unicode
  database: Project_Rails
  username: postgres
  password: rp07051998

production:
  adapter: postgresql
  encoding: unicode
  database: Project_Rails
  username: postgres
  password: rp07051998